version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      ZClaN+rmSQFAT84Ztb+FT7bxpifUUrGHNgW2yjucxFrd/v7mu1NrMXLexkusVhqPyXss8UC7o+qoKXHm71/DTdBKMLNlAyA9rRo+qbiZdrloPSs68DxaIZYmMzP7VymPLgf/0pJPg99r8Gp2sQEfknl8a39j/f3VkUzf4Ff0HtI=
